Add missing requiring uri library
It causes the following error:

    NameError: uninitialized constant URI::Parser::Generic
    /usr/lib/ruby/1.9.1/uri/common.rb:218:in `parse'
    /usr/lib/ruby/1.9.1/uri/common.rb:747:in `parse'
    ...